In [3]:
import numpy as np
import pandas as pd

In [4]:
dataset = pd.read_csv("./data/framingham.csv")
dataset.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [5]:
dataset.dropna(axis=0, inplace=True)

In [6]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [8]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='liblinear')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[760   8]
 [135  12]]


In [10]:
from sklearn.metrics import accuracy_score as score
print('Accuracy')
print(score(y_test,y_pred)*100)

Accuracy
84.37158469945355


# Logistic Regression Example

In this tutorial, we'll walk through how to use our automatic differentiation engine to create and train a logistic regression model to predict heart disease. 

The data can be found [here](https://www.kaggle.com/saxarchit/logistic-regression).

Our goal here is not to create the best model to fit our data, but to simply show how to use our automatic differentiation engine to create, train, and test a logistic regression model. Thus, our model will be very simplistic for pedagogical purposes.

# Data Preprocessing

We'll first take look at our data, validate it, and preprocess it to be in a form appropriate to use with our automatic differentiation engine.

Feel free to skip this section as it doesn't directly relate to how to use our automatic differentiation engine.

Let's first import some necessary libraries.

In [9]:
from autograd import Variable, LinearLayer
import autograd
from tqdm import tqdm
import pandas as pd
import numpy as np
import random

Let's load the data. 

In [10]:
csv_path = './data/framingham.csv'
df = pd.read_csv(csv_path)
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

Let's clean our data.

Since this tutorial is focused on using our automatic differentiaion engine rather than on machine learning itself, we'll avoid doing a deep dive into the data analysis rationalizing the methods we here to clean our data. More examples of analysis on this dataset can be found [here](https://www.kaggle.com/amanajmera1/framingham-heart-study-dataset/notebooks).

Let's first drop any null values.

In [11]:
df.dropna(axis=0, inplace=True)
assert df.isnull().sum().sum() == 0

Let's also normalize our input data. 

In [12]:
continuous_input_columns = ['age', 'education', 'cigsPerDay', 'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose']
for input_column_name in continuous_input_columns:
    mean = df[input_column_name].mean()
    std_dev = df[input_column_name].std()
    values = df[input_column_name]
    df[input_column_name] = (values-mean)/std_dev
df.head()

male       age  education  currentSmoker  cigsPerDay  BPMeds  \
0     1 -1.232411   1.974939              0   -0.757065     0.0   
1     0 -0.414848   0.019247              0   -0.757065     0.0   
2     1 -0.181259  -0.958599              1    0.920563     0.0   
3     0  1.337073   0.997093              1    1.759377     0.0   
4     0 -0.414848   0.997093              1    1.172207     0.0   

   prevalentStroke  prevalentHyp  diabetes   totChol     sysBP     diaBP  \
0        -0.075976     -0.672768 -0.166761 -0.948978 -1.193947 -1.078733   
1        -0.075976     -0.672768 -0.166761  0.298253 -0.514811 -0.160096   
2        -0.075976     -0.672768 -0.166761  0.184868 -0.220518 -0.243609   
3        -0.075976      1.485991 -0.166761 -0.268670  0.798187  1.009079   
4        -0.075976     -0.672768 -0.166761  1.091946 -0.107329  0.090441   

        BMI  heartRate   glucose  TenYearCHD  
0  0.292010   0.356321 -0.203016           0  
1  0.724911   1.608249 -0.244850           0  
2 -0.108914  -0.060988 -0.495852           0  
3  0.688016  -0.895606  0.884661           1  
4 -0.659878   0.773630  0.131654           0

Our model will be very simple. We'll create a logistic regression model that takes in a value from each column and will return whether or not the patient has a 10 year risk of heart disease.

Our automatic differentiation engine expects numpy arrays. 

Let's convert the data into two numpy arrays, one for the inputs and one for the outputs.

In [13]:
input_df = df[['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds', 'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP', 'diaBP', 'BMI', 'heartRate', 'glucose']]
output_df = df['TenYearCHD']
input_matrix = input_df.values
output_vector = output_df.values

In [14]:
type(input_matrix)

numpy.ndarray

In [15]:
input_matrix.shape

(3658, 15)

In [16]:
type(output_vector)

numpy.ndarray

In [17]:
output_vector.shape

(3658,)

Let's now split our data into a training set and test set. We'll use 70% of our data for training and 30% for testing. We'll manually set the random seeds for reproducibility purposes.

In [18]:
random.seed(0)
np.random.seed(0)

row_count = input_matrix.shape[0]
row_indices = list(range(row_count))
random.shuffle(row_indices)

last_training_row_position = round(row_count*0.75)
training_indices = row_indices[:last_training_row_position+1]
testing_indices = row_indices[last_training_row_position+1:]

training_input_matrix = input_matrix[training_indices]
training_output_vector = output_vector[training_indices]
testing_input_matrix = input_matrix[testing_indices]
testing_output_vector = output_vector[testing_indices]

A logistic regression model can be implemented as a dense linear layer with a sigmoid activation. 

This is how we'll implement our model. 

In [19]:
sigmoid = lambda x: np.exp(x)/(np.exp(x)+1)
linear_layer = LinearLayer(15, 1)

number_of_epochs = 100
learning_rate = 1e-5
sgd = autograd.optimizer.SGD(learning_rate)

for epoch in range(number_of_epochs):
    for i, (x, y) in enumerate(list(zip(training_input_matrix, training_output_vector))):
        linear_result = linear_layer(x)
        y_hat = sigmoid(linear_result)
        diff = (y_hat - y)
        loss = diff ** 2
        print('\n'*1)
        #print(f"x \n{repr(x)}\n")
        print(f"linear_layer.matrix \n{repr(linear_layer.matrix)}\n")
        print(f"linear_layer.biases \n{repr(linear_layer.biases)}\n")
        #print(f"linear_result \n{repr(linear_result)}\n")
        var2grad = sgd.take_training_step(loss)
        #print(f"linear_layer.matrix \n{repr(linear_layer.matrix)}\n")
        #print(f"linear_layer.biases \n{repr(linear_layer.biases)}\n")
        if i == 0:
            print(f"var2grad[linear_layer.matrix] \n{repr(var2grad[linear_layer.matrix])}\n")
            print(f"var2grad[linear_layer.biases] \n{repr(var2grad[linear_layer.biases])}\n")
            print(f"loss {loss}")

var2grad[linear_layer.matrix] 
array([[   0.        ],
       [ 112.04130692],
       [  -1.93295835],
       [   0.        ],
       [  76.03204247],
       [   0.        ],
       [   7.63030472],
       [-149.23796636],
       [  16.7477893 ],
       [  74.80883302],
       [  47.15538327],
       [ -92.95457485],
       [-100.71643243],
       [ -94.45980339],
       [  -0.61791434]])

var2grad[linear_layer.biases] 
array([[-100.42995209]])

loss Variable([[0.63944802]])


/Users/pnguyen/code/one_off_code/autograd/autograd/variable.py:545: RuntimeWarning: overflow encountered in exp
  exp_result = np_exp(operand_data, **kwargs)
/Users/pnguyen/code/one_off_code/autograd/autograd/variable.py:407: RuntimeWarning: invalid value encountered in true_divide
  quotient = np_divide(dividend_data, divisor_data, **kwargs)


var2grad[linear_layer.matrix] 
array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]])

var2grad[linear_layer.biases] 
array([[nan]])

loss Variable([[nan]])
var2grad[linear_layer.matrix] 
array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]])

var2grad[linear_layer.biases] 
array([[nan]])

loss Variable([[nan]])
var2grad[linear_layer.matrix] 
array([[nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan],
       [nan]])

var2grad[linear_layer.biases] 
array([[nan]])

loss Variable([[nan]])
var2grad[linear_layer.matrix] 
array([[nan],
       [nan],
  

In [20]:
sigmoid = lambda x: np.exp(x)/(np.exp(x)+1)
linear_layer = LinearLayer(15, 1)

First, we'll need to establish some hyperparameters for training our linear regression model. We'll be using stochastic gradient descent.

In practice, we might use various batch sizes or shuffle our training data between epochs, but we'll forgo this for the sake of simplicity as the purposes of this tutorial is to show how to use our automatic differentiation engine rather than finding the best model possible.

In [21]:
number_of_epochs = 1000
learning_rate = 1e-10
sgd = autograd.optimizer.SGD(learning_rate)

Let's write our training loop. 

In [ ]:
epoch_iterator = tqdm(range(number_of_epochs))
for epoch_index in epoch_iterator:
    for x, y in zip(training_input_matrix, training_output_vector):
        linear_result = linear_layer(x)
        y_hat = sigmoid(linear_result)
        diff = (y_hat - y)
        loss = diff ** 2
        var2grad = sgd.take_training_step(loss)
    epoch_iterator.set_description(f'Loss: {loss.sum().data:.8f}')
    epoch_iterator.refresh()

Loss: nan:  40%|███▉      | 399/1000 [03:10<04:28,  2.24it/s]

Let's now see how our model performs on our test set.

In [ ]:
mean_testing_loss = 0
for x, y in zip(testing_input_matrix, testing_output_vector):
    y_hat = np.sum(np.multiply(y, weights) + biases)
    loss = (y_hat - y) ** 2
    mean_testing_loss += loss.data
mean_testing_loss /= len(testing_output_vector)

In [ ]:
mean_testing_loss

Let's look at a few random results to sanity check our mode. 

In [ ]:
random_test_examples = random.sample(list(zip(testing_input_matrix, testing_output_vector)), 10)
for x, y in random_test_examples:
    y_hat = np.sum(np.multiply(y, weights) + biases)
    print()
    print(f'y_hat: {y_hat.data}')
    print(f'y:     {y}')